-- Insert Records into Books Table
USE book_inventory;

INSERT INTO books (title, author, quantity) VALUES
('The Great Gatsby', 'F. Scott Fitzgerald', 10),
('To Kill a Mockingbird', 'Harper Lee', 8),
('1984', 'George Orwell', 15),
('Pride and Prejudice', 'Jane Austen', 12),
('The Catcher in the Rye', 'J.D. Salinger', 7),
('Moby-Dick', 'Herman Melville', 5),
('War and Peace', 'Leo Tolstoy', 9),
('The Odyssey', 'Homer', 11),
('Brave New World', 'Aldous Huxley', 6),
('Crime and Punishment', 'Fyodor Dostoevsky', 14),
('Jane Eyre', 'Charlotte Brontë', 10),
('The Hobbit', 'J.R.R. Tolkien', 20),
('Fahrenheit 451', 'Ray Bradbury', 13),
('Wuthering Heights', 'Emily Brontë', 9),
('The Lord of the Rings', 'J.R.R. Tolkien', 25),
('The Brothers Karamazov', 'Fyodor Dostoevsky', 7),
('Animal Farm', 'George Orwell', 16),
('Dracula', 'Bram Stoker', 5),
('The Iliad', 'Homer', 10),
('The Divine Comedy', 'Dante Alighieri', 4),
('A Tale of Two Cities', 'Charles Dickens', 11),
('Les Misérables', 'Victor Hugo', 6),
('Great Expectations', 'Charles Dickens', 9),
('Frankenstein', 'Mary Shelley', 8),
('Don Quixote', 'Miguel de Cervantes', 7),
('The Grapes of Wrath', 'John Steinbeck', 6),
('The Old Man and The Sea', 'Ernest Hemingway', 14),
('The Picture of Dorian Gray', 'Oscar Wilde', 13),
('Sense and Sensibility', 'Jane Austen', 9),
('David Copperfield', 'Charles Dickens', 8),
('Little Women', 'Louisa May Alcott', 7),
('Slaughterhouse-Five', 'Kurt Vonnegut', 6),
('The Alchemist', 'Paulo Coelho', 17),
('The Count of Monte Cristo', 'Alexandre Dumas', 12),
('Gone with the Wind', 'Margaret Mitchell', 5),
('Memoirs of a Geisha', 'Arthur Golden', 8),
('The Kite Runner', 'Khaled Hosseini', 10),
('Life of Pi', 'Yann Martel', 9),
('The Road', 'Cormac McCarthy', 7),
('Beloved', 'Toni Morrison', 6),
('Of Mice and Men', 'John Steinbeck', 15),
('Catch-22', 'Joseph Heller', 8),
('The Sun Also Rises', 'Ernest Hemingway', 6),
('The Call of the Wild', 'Jack London', 11),
('Rebecca', 'Daphne du Maurier', 7),
('The Secret Garden', 'Frances Hodgson Burnett', 9),
('Treasure Island', 'Robert Louis Stevenson', 10),
('The Time Machine', 'H.G. Wells', 5),
('A Clockwork Orange', 'Anthony Burgess', 7),
('The Scarlet Letter', 'Nathaniel Hawthorne', 8),
('The Jungle Book', 'Rudyard Kipling', 12),
('Persuasion', 'Jane Austen', 9),
('Middlemarch', 'George Eliot', 6),
('Madame Bovary', 'Gustave Flaubert', 5),
('Anna Karenina', 'Leo Tolstoy', 8),
('The Hunchback of Notre-Dame', 'Victor Hugo', 7),
('Ulysses', 'James Joyce', 5),
('Dubliners', 'James Joyce', 6),
('The Metamorphosis', 'Franz Kafka', 10),
('Heart of Darkness', 'Joseph Conrad', 7),
('The Stranger', 'Albert Camus', 8),
('The Trial', 'Franz Kafka', 6),
('East of Eden', 'John Steinbeck', 9),
('The Sound and the Fury', 'William Faulkner', 5),
('Their Eyes Were Watching God', 'Zora Neale Hurston', 6),
('Native Son', 'Richard Wright', 7),
('Invisible Man', 'Ralph Ellison', 8),
('The Bell Jar', 'Sylvia Plath', 9),
('The Color Purple', 'Alice Walker', 10),
('Siddhartha', 'Hermann Hesse', 8),
('One Hundred Years of Solitude', 'Gabriel García Márquez', 12),
('Love in the Time of Cholera', 'Gabriel García Márquez', 11),
('The House of the Spirits', 'Isabel Allende', 9),
('The Master and Margarita', 'Mikhail Bulgakov', 5),
('The Unbearable Lightness of Being', 'Milan Kundera', 6),
('Blindness', 'José Saramago', 7),
('Norwegian Wood', 'Haruki Murakami', 8),
('Kafka on the Shore', 'Haruki Murakami', 10),
('The Wind-Up Bird Chronicle', 'Haruki Murakami', 6),
('A Man Called Ove', 'Fredrik Backman', 9),
('Beartown', 'Fredrik Backman', 7),
('The Night Circus', 'Erin Morgenstern', 8),
('Circe', 'Madeline Miller', 9),
('The Song of Achilles', 'Madeline Miller', 7),
('Eleanor Oliphant Is Completely Fine', 'Gail Honeyman', 6),
('The Midnight Library', 'Matt Haig', 11),
('Anxious People', 'Fredrik Backman', 5),
('Project Hail Mary', 'Andy Weir', 8),
('The Martian', 'Andy Weir', 10),
('Daisy Jones & The Six', 'Taylor Jenkins Reid', 7),
('Malibu Rising', 'Taylor Jenkins Reid', 6),
('Verity', 'Colleen Hoover', 9),
('It Ends with Us', 'Colleen Hoover', 10),
('Reminders of Him', 'Colleen Hoover', 8),
('Ugly Love', 'Colleen Hoover', 7),
('November 9', 'Colleen Hoover', 6),
('Regretting You', 'Colleen Hoover', 5),
('All Your Perfects', 'Colleen Hoover', 8);
